src/components/editor/EditorController.vue
src/components/editor/EditorMain.vue
src/model/KeyConfig.ts

やったこと:
- ページ操作の導入( #3 )
- 下移動の現在位置バグ解消( #7 )
- 5keyの入力方式変更
- FirstNumの入力桁を2桁に

ページ操作、行移動のバグ解消

---

public/style.css
src/components/editor/EditorController.vue
src/components/editor/EditorMain.vue
src/components/editor/MusicPlayer.ts
src/components/editor/ScoreConverter.ts
src/model/ScoreData.ts
src/model/Timing.ts
src/test/components/editor/ScoreConverterSpec.ts

FirstNumをAdjustmentとStartNumに分割

---

src/components/editor/EditorController.vue
src/components/editor/EditorMain.vue
src/components/editor/service/MusicService.ts
src/components/editor/service/NoteService.ts
src/components/editor/service/PageScoreService.ts
src/components/editor/service/ScoreConvertService.ts
src/components/editor/service/ScoreConverterService.ts
src/components/editor/service/SpeedPieceService.ts
src/pages/Editor.vue
src/test/components/editor/ScoreConverterSpec.ts

EditorMainのスリム化

---

public/style.css
src/components/editor/EditorConstant.ts
src/components/editor/EditorMain.vue
src/components/editor/helper/Calculator.ts
src/components/editor/service/NoteService.ts
src/components/editor/service/ScoreConvertService.ts
src/test/components/editor/helper/CalculatorSpec.ts
src/test/components/editor/service/NoteServiceSpec.ts
src/test/components/editor/service/ScoreConvertSpec.ts
src/test/components/editor/service/SpeedPieceServiceSpec.ts
src/test/components/editor/service/testScoreData.ts

現在位置のフレーム、時間表示

---

public/style.css
src/components/editor/EditorController.vue
src/components/editor/service/LevelCalcService.ts
src/components/editor/service/ScoreConvertService.ts
src/test/components/editor/service/LevelCalcServiceSpec.ts

レベル計算ツール移植試作

---

src/components/editor/EditorController.vue
src/components/editor/service/ScoreConvertService.ts
src/model/ScoreData.ts
src/test/components/editor/service/testScoreData.ts

譜面番号を出力に追加できるようにする

---

public/style.css
src/components/editor/EditorController.vue
src/components/editor/EditorMain.vue
src/components/editor/EditorOption.vue
src/components/editor/service/MusicService.ts

オプション設定の追加

---

public/style.css
src/components/common/createCustomKeyConfig.ts
src/components/configure/ConfigureMain.vue
src/components/configure/ConfigureUploader.vue
src/components/editor/EditorController.vue
src/components/editor/EditorMain.vue
src/components/editor/service/NoteService.ts
src/components/editor/service/ScoreConvertService.ts
src/components/start/StartMain.vue
src/model/KeyConfig.ts
src/model/KeyKind.ts
src/pages/Configure.vue
src/pages/Editor.vue
src/router.ts

LocalStorageにコンフィグファイルを保存できるようにする

---

src/components/editor/EditorMain.vue
src/components/start/StartMain.vue
src/model/ScoreData.ts
src/router.ts

セーブファイル内のデータを参照して自動でキー数を設定

---

public/style.css
src/components/editor/EditorController.vue
src/components/start/StartMain.vue

LocalStorageにリカバリーデータを保存する機能

---

src/components/editor/EditorMain.vue
src/components/editor/service/CurrentPositionService.ts
src/components/editor/service/PageScoreService.ts

ページの挿入・削除機能

---

src/components/editor/EditorMain.vue
src/model/KeyConfig.ts

下部に入力キーを表示する

---

src/components/editor/EditorController.vue
src/components/editor/EditorMain.vue
src/components/editor/helper/undo.ts
src/components/editor/service/NoteService.ts
src/components/editor/service/PageScoreService.ts
src/model/OperationQueue.ts
src/test/components/editor/service/NoteServiceSpec.ts

- コピーペーストはCtrl必須にする
- undo機能の追加

CTRL系のアクションの改善・追加

---

src/components/editor/EditorController.vue
src/components/editor/EditorOption.vue

feat: 音量をローカルで保存するように

---

src/components/editor/EditorMain.vue

Space、Bキーのリバース時進行方向を修正

---

public/style.css
src/components/editor/EditorController.vue
src/components/editor/EditorSave.vue
src/components/start/StartLoad.vue
src/components/start/StartMain.vue

feat: オンラインパスの履歴を保存する

---

public/style.css
src/components/configure/ConfigureDesign.vue
src/components/editor/EditorMain.vue
src/components/editor/service/NoteService.ts

一定時間内に複数のキーを押したとき、同時押しとして入力/削除されるようにしました。
同時押しとみなす時間は Configure -> Simultaneous Threshold(msec) にて設定できます。
threshold を -1 に設定すると無効にできます。
多重同時押しが簡単に入力/削除できるようになります。
高速入力時に誤判定が起こり得ますが、閾値を十分短くすることで実用上問題にはならないと思います。
英語力が無いため simultaneous という語が適当かどうかはよく分かりません(すみません)。

feat: 同時に押したとき同時押しが入力できるようにする

---

README.md
src/components/editor/EditorMain.vue

issue #88
コメントに書いたやつですが一応PRにしておきます

ページ終端で同時押し入力できないことがある問題の修正

---

public/style.css
src/components/editor/EditorController.vue
src/components/editor/service/ScoreRevivalService.ts
src/components/start/StartMain.vue
src/components/start/StartUploader.vue

thanks https://github.com/superkuppabros/danoni-editor/pull/93
一部修正済

譜面データをクリップボードから読み込めるようにする+α

---

src/components/editor/EditorMain.vue
src/components/editor/service/MusicService.ts

中途半端になっていた部分を完結。
副作用として、倍速再生時にピッチも変わるようになった。
(一応技術的にはそうならないように出来るらしいが無理そう)

WebAudioAPIで楽曲を再生する

---

src/components/editor/EditorMain.vue
src/components/editor/service/MusicService.ts

再生しながらオプション画面でボリュームや再生速度を変更したときその場で反映されるようにしました。

ボリュームと再生速度を即時反映する

---

src/components/editor/EditorController.vue

fix: keyが定義されていないときのエラーハンドリングを追加

---

package-lock.json
package.json

ライブラリアップデート
